# Generated by Django 3.2.9 on 2021-12-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference_code', models.IntegerField()),
                ('description', models.CharField(default='Dummy Product', max_length=255)),
                ('is_offert', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('XS', 'EXTRA SMALL'), ('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], max_length=2)),
                ('image', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
